create table questions
(
    id int primary key generated by default as identity,
    question varchar,
    author varchar,
    time timestamp
);

create table comments(
                         id int generated by default as identity ,
                         question_id int references questions(id),
                         comment varchar,
                         author varchar,
                         time timestamp,
                         upvote int,
                         downvote int
)